# Generated by Django 5.2.11 on 2026-02-27 06:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.CharField(default=core.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='installation',
            name='id',
            field=models.CharField(default=core.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repair',
            name='id',
            field=models.CharField(default=core.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
