# Generated by Django 5.2.12 on 2026-03-09 01:48

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.CharField(default=core.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, db_index=True, max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Registrasi User'), ('create_repair', 'Buat Laporan Error'), ('update_repair', 'Update Repair'), ('create_installation', 'Instalasi Perangkat'), ('import_data', 'Import Data'), ('export_data', 'Export Data')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.user')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'ActivityLog',
                'ordering': ['-timestamp'],
            },
        ),
    ]
